### ISSUE TITLE
Figure 8, 11 & 13 analysis.ipynb

### ISSUE THREAD

**Issue by thorerismann** [thorerismann/flora-buckets#28]
**Modify the legend in 8 to include the following dictionary:**

legendkey = {"ongen" = "identified to genus", "ni" = "neophyte", "ns" = "culturally significant neophyte","WL = Watchlist", "BL" = "Blacklist", "LC = Least Concern", VU = "vulnerable", "NT" = "Near Threatened", "EN" = "Endangered","NE" = "Not Evaluated", "DD" = Data Deficient" }

**legendkey for 11:**

legendkey = {"WL = Watchlist", "BL" = "Blacklist"}

**legend in 13:**

legendkey = {"LC = Least Concern", VU = "vulnerable", "NT" = "Near Threatened", "EN" = "Endangered","NE" = "Not Evaluated", "DD" = Data Deficient" }

**Comment by hammerdirt-analyst** [comment]
ref:  newfeautures 91a5269
