### ISSUE TITLE
Figure 13 analysis.ipynb 

### ISSUE THREAD

**Issue by thorerismann** [thorerismann/flora-buckets#39]
Deprecation warning : /tmp/ipykernel_4372/3455561462.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(add_these)

**Comment by hammerdirt-analyst** [comment]
see #40

**Comment by hammerdirt-analyst** [comment]
The method is changed to:

```
# cahnge this to a df
add_these = pd.DataFrame([{period:x, column:aval, "data":0} for x in add_dates])

# replace append with concat
d = pd.concat([data, add_these])
```
