### ISSUE TITLE
Germination.ipynb - 3rd code block

### ISSUE THREAD

**Issue by thorerismann** [thorerismann/flora-buckets#40]
Deprecation warning:

/tmp/ipykernel_7355/3126014015.py:15: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.   conc["sprouted"] = conc[ccounts].max(axis=1)

**Comment by hammerdirt-analyst** [comment]
This is a known [issue](https://github.com/pandas-dev/pandas/issues/26927) you can fix it like this:

``concrete["sprouted"] = concrete[counts].max(axis=1, numeric_only=True)``

Add numeric_only = True even if you have all numeric columns when you are reducing (sum, mean, max etc... ) for a group of columns.

**Comment by hammerdirt-analyst** [comment]
[satmar5 0221443] raise issue -missing images and columns refs
